# Generated by Django 3.2.13 on 2022-07-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_text',
            field=models.CharField(max_length=50, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_text',
            field=models.CharField(max_length=50, null=True, verbose_name='Тип'),
        ),
    ]
