# Generated by Django 3.2.13 on 2022-07-18 19:04

from django.db import migrations, models
import webapp.validate


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.CharField(default='Unknown', max_length=50, validators=[webapp.validate.validate_author], verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=3000, null=True, validators=[webapp.validate.validate_description], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=100, null=True, validators=[webapp.validate.validate_summary], verbose_name='Pезюме'),
        ),
    ]
