# Generated by Django 3.2.13 on 2022-07-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20220719_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата создания')),
                ('end_date', models.DateField(blank=True, verbose_name='Дата окончания')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
