# Generated by Django 3.2.13 on 2022-07-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20220711_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='status1',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='type1',
        ),
        migrations.AlterField(
            model_name='status',
            name='status_text',
            field=models.CharField(default=1, max_length=50, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='type',
            name='type_text',
            field=models.CharField(default=1, max_length=50, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
