# Generated by Django 4.1 on 2022-08-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('add_users_to_the_project', 'добавлять пользователей в проект'), ('remove_users_from_the_project', 'удалять пользователей из проекта')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
