# Generated by Django 3.2.13 on 2022-07-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20220713_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tags',
            new_name='tags_old',
        ),
    ]
