# Generated by Django 3.2.13 on 2022-07-10 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20220711_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status1',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type1',
        ),
        migrations.AddField(
            model_name='status',
            name='status1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='webapp.status', verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='type1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='type', to='webapp.type', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
