# Generated by Django 3.2.13 on 2022-07-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_tags_task_tags_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags_old',
            field=models.ManyToManyField(blank=True, related_name='old_tasks', through='webapp.TaskTag', to='webapp.Tag'),
        ),
    ]
