# Generated by Django 3.2.13 on 2022-07-10 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20220711_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='webapp.task', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type', to='webapp.task', verbose_name='Тип'),
        ),
    ]
