# Generated by Django 3.2.13 on 2022-07-28 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_task_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='webapp.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='webapp.Tag'),
        ),
        migrations.AlterField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='types', to='webapp.Types'),
        ),
        migrations.AlterModelTable(
            name='project',
            table='webapp_project',
        ),
    ]
