# Generated by Django 3.2.13 on 2022-07-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], max_length=60, verbose_name='Статус'),
        ),
    ]
