# Generated by Django 3.2.13 on 2022-07-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Названия задачи'),
            preserve_default=False,
        ),
    ]
