# Generated by Django 3.2.13 on 2022-07-13 19:19

from django.db import migrations


def transfer_tags(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    for task in Task.objects.all():
        task.tags.set(task.tags_old.all())


def rollback_transfer(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    for task in Task.objects.all():
        task.tags_old.set(task.tags.all())


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_task_tags'),
    ]

    operations = [
        migrations.RunPython(transfer_tags, rollback_transfer)
    ]
