# Generated by Django 3.2.13 on 2022-07-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20220714_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tags_old',
        ),
        migrations.DeleteModel(
            name='TaskTag',
        ),
    ]
