# Generated by Django 3.2.13 on 2022-07-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20220714_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=100, null=True, verbose_name='Pезюме'),
        ),
    ]
